
/* array of all defined inputs to SQLColAttributes
 * source: ODBC 3.5 Developers Guide by Roger E Sanders ISBN 0-07-058087-1
 * author: Dennis Box, dbox@fnal.gov
 * $Id: SQLColAttributesIn.h,v 1.2 2002/05/31 19:54:59 dbox Exp $
 */


SQLColAttributesIn[] = {
SQL_COLUMN_COUNT,
SQL_COLUMN_NAME,
SQL_COLUMN_TYPE,
SQL_COLUMN_LENGTH,
SQL_COLUMN_PRECISION,
SQL_COLUMN_SCALE,
SQL_COLUMN_DISPLAY_SIZE,
SQL_COLUMN_NULLABLE,
SQL_COLUMN_UNSIGNED,
SQL_COLUMN_MONEY,
SQL_COLUMN_UPDATABLE,
SQL_COLUMN_AUTO_INCREMENT,
SQL_COLUMN_CASE_SENSITIVE,
SQL_COLUMN_SEARCHABLE,
SQL_COLUMN_TYPE_NAME,
SQL_COLUMN_TABLE_NAME,
SQL_COLUMN_OWNER_NAME,
SQL_COLUMN_QUALIFIER_NAME,
SQL_COLUMN_LABEL,
SQL_COLATT_OPT_MAX,
SQL_COLUMN_DRIVER_START,
SQL_COLATT_OPT_MIN
};
#define SQLColAttributesInSIZE sizeof(SQLColAttributesIn)/sizeof(SQLColAttributesIn[0]) 
